spring:
  application:
    name: Spring AI Basics
  ai:
    openai:
      api-key: ${OPENROUTER_API_KEY}
      base-url: https://openrouter.ai/api/v1
      chat:
        options:
          model: qwen/qwen3.7-flash
      embedding:
        enabled: false
    #Chat memory table creation properties
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always
  logging:
    level:
      org.springframework.ai: INFO
  #JDBC Connection
  datasource:
    url: jdbc:postgresql://localhost:5432/springai
    username: postgres
    password:
    driver-class-name: org.postgresql.Driver




